version: '3.8'

services:
  spring-boot-app:
    image: hyeonda02/test-server:latest
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://test:testPW@mongo:27017/testdb
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: testPW
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

